name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' # Specify the desired version

    - name: Build and Test
      run: |
        dotnet build YourProject.sln
        dotnet test YourProject.Tests.csproj
